[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    # see https://github.com/numpy/numpy/pull/18389
    "wheel>=0.36.2",

    # Cython 3.0 is the next version after 0.29, and a major change,
    # we forbid it until we can properly test against it
    "Cython>=0.29.21,<3.0",
    "oldest-supported-numpy",
]

[tool.setuptools_scm]

[tool.black]
line-length = 88
target-version = ['py38']
include = '''
/(
    \.pyi?$
  | scripts/*
)/
'''
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
combine_as_imports = true
skip =  ["venv", "benchmarks"]
known_third_party = [
  "IPython",
  "numpy",
  "sympy",
  "matplotlib",
  "unyt",
  "git",
  "yaml",
  "dateutil",
  "requests",
  "coverage",
  "pytest",
  "astropy",
  "scipy",
  "pathlib",
  "yt",
  "pyxsim"
]
known_first_party = ["soxs"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
