#!/usr/bin/env python

import argparse
import os
from sox import make_astrophysical_background, write_simput_catalog

parser = argparse.ArgumentParser(description='Create a SIMPUT photon list of a point source from'+
                                             'a spectrum supplied in a file.')
parser.add_argument("simput_prefix", type=str,
                    help='The prefix of the SIMPUT file to be used as the root of the '+
                         'catalog. If it does not exist, it will be created.')
parser.add_argument("phlist_prefix", type=str,
                    help='The prefix of the photon list file to be written.')
parser.add_argument("ra_pnt", type=float, help="The right ascension of the source in degrees.")
parser.add_argument("dec_pnt", type=float, help="The declination of the source in degrees.")
parser.add_argument("fov", type=float, help='The width of the field of view in arcminutes.')
parser.add_argument("exp_time", type=float, help='The exposure time to use, in seconds.')
parser.add_argument("--bkgnd_file", type=str,
                    help="The file containing the spectrum to be used to make the background.")
parser.add_argument("--area", type=float, default=30000.0, help='The collecting area to use, in cm^2.')
parser.add_argument("--clobber", action='store_true',
                    help='Whether or not to clobber an existing file with the same name.')

args = parser.parse_args()

append = os.path.exists(args.simput_prefix+"_simput.fits")

events = make_astrophysical_background(args.ra_pnt, args.dec_pnt, args.fov,
                                       args.exp_time, bkgnd_file=args.bkgnd_file,
                                       area=args.area)

write_simput_catalog(args.simput_prefix, args.phlist_prefix,
                     args.exp_time, args.area, events["ra"], 
                     events["dec"], events["energy"], 
                     append=append, clobber=args.clobber)
