name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "doc/**"
      - README.md

defaults:
    run:
        shell: bash

env:
    ANSWER_VER: 15

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: [ '3.11' ]
                numpy-version: ['1', '2']
                include:
                    - os: ubuntu-latest
                      python-version: '3.12'
                      numpy-version: '1'
                    - os: ubuntu-latest
                      python-version: '3.10'
                      numpy-version: '1'
                    - os: ubuntu-latest
                      python-version: 3.9
                      numpy-version: '1'
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0
            - uses: s-weigand/setup-conda@v1
              with:
                  update-conda: true
                  conda-channels: conda-forge
                  activate-conda: true
                  python-version: ${{matrix.python-version}}
            - name: Install dependencies and soxs
              shell: bash
              env:
                  mode: testing
              run: source ./tests/ci_install.sh
            - name: Run Tests
              run: py.test -vv soxs/tests
